add branch, add expanded_form.py in prealgebra
damariion/learnmaths pull request #11
Opened 2024-04-13 20:05 UTC by BaderSarah

2024-04-13 20:16 UTC, damariion requested changes

2024-04-13 20:16 UTC, damariion commented on src/prealgebra/expanded_form.py
> +        solutions   = (solution,),
Should be: solutions = solution, and not (solution,) because you already create a tuple before the return statement. So solutions now holds: ((first_notation, second_notation),) tuple[tuple[str, ...]]

2024-04-13 20:16 UTC, damariion commented on src/prealgebra/expanded_form.py
> +    for digit in number[:-1]:
Please add logic such that 0's aren't shown. (no: 0 x 10000 or ... + 0 + ...), also use '*' for multiplication, not 'x'.

2024-04-13 20:38 UTC, damariion requested changes

2024-04-13 20:38 UTC, damariion commented on src/prealgebra/expanded_form.py
> +        solutions   = solutions
This will result in a syntax error, "solutions" should be "solutions,". Do you test your code baby?

2024-04-13 20:38 UTC, damariion commented on src/prealgebra/expanded_form.py
> +            second_notation_notation += ""
second_notation_notation doesn't exist?

2024-04-13 20:38 UTC, damariion commented on src/prealgebra/expanded_form.py
> +            first_notation += f"{digit} * {10 ** power} + "
Logic error, this will omit the last item

2024-04-13 20:38 UTC, damariion commented on src/prealgebra/expanded_form.py
> +            second_notation += f"{int(digit) * (10 ** power)} + "
With a number like: 650 you'd still get 600 + 50 + 0. So, again- please add logic to ignore trailing zeros.

2024-04-14 17:03 UTC, BaderSarah commented on src/prealgebra/expanded_form.py
> +        solutions   = solutions
This was overlooked, has been dealt with. Thank you for bringing it to my attention.

2024-04-14 17:04 UTC, BaderSarah commented on src/prealgebra/expanded_form.py
> +            second_notation_notation += ""
It indeed does not, my bad.

2024-04-14 17:40 UTC, BaderSarah commented on src/prealgebra/expanded_form.py
> +            second_notation += f"{int(digit) * (10 ** power)} + "
Will do better, thanks for the feedback!

2024-04-14 17:48 UTC, damariion requested changes

2024-04-14 17:48 UTC, damariion commented on src/prealgebra/expanded_form.py
>      number = [*range(0, 10)]
Make the number a bit smaller, best just generate a random int.

2024-04-14 18:51 UTC, closed without merging